version: '3'

services:
  nginx_proxy:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./MySQL/db:/var/lib/mysql
  pma:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - '81:80'
  wordpress-itstep-first:
    depends_on:
      - mysql
    restart: always
    image: wordpress
    ports:
      - '82:80'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./Wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./Wordpress/wp-content:/var/www/html/wp-content
  wordpress-itstep-second:
    depends_on:
      - mysql
    restart: always
    image: wordpress
    ports:
      - '83:80'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./Wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./Wordpress/wp-content:/var/www/html/wp-content
  