version: '3'

services:
  nginx_proxy:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./MySQL/db:/var/lib/mysql
      - ./MySQL/init:/docker-entrypoint-initdb.d
  pma:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - '81:80'
  wordpress-itstep-first:
    depends_on:
      - mysql
    restart: always
    image: wordpress
    ports:
      - '82:80'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./Wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./Wordpress/wp-content:/var/www/html/wp-content
  wordpress-itstep-second:
    depends_on:
      - mysql
    restart: always
    image: wordpress
    ports:
      - '83:80'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./Wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./Wordpress/wp-content:/var/www/html/wp-content
  joomla:
    image: joomla
    depends_on:
      - mysql
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: password
    ports:
      - '84:80'
  opencart:
    image: bitnami/opencart
    depends_on:
      - mysql
    environment:
      OPENCART_DATABASE_HOST: mysql
      OPENCART_DATABASE_NAME: opencart
      OPENCART_DATABASE_USER: opencart
      OPENCART_DATABASE_PASSWORD: password
      OPENCART_HOST: opencart.itstep.loc
      OPENCART_ENABLE_HTTPS: yes
    ports:
      - '85:8080'
    volumes:
      - opencart:/bitnami/opencart
  
volumes:
  opencart:
    driver: local