version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.mysite.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.mysite.com/'
        registry_external_url 'https://registry.mysite.com/'
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.mysite_bundle.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.mysite.com.key"
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "registry.mysite.com"
        registry['enable'] = true
        registry['registry_http_addr'] = "localhost:5000"
        registry['log_directory'] = "/var/log/gitlab/registry"
        registry['env_directory'] = "/opt/gitlab/etc/registry/env"
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 443
        registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/registry.mysite_bundle.crt"
        registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/registry.mysite.com.key"
        gitlab_kas_external_url "ws://gitlab.mysite.com/-/kubernetes-agent/"
        gitlab_kas['enable'] = true
        gitlab_kas['env'] = {
           'SSL_CERT_DIR' => "/opt/gitlab/embedded/ssl/certs",}
        # Add any other gitlab.rb configuration here, each on its own line
    networks:
      gitlab-net:
        aliases:
          - gitlab.mysite.com
          - registry.mysite.com
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - './certs:/etc/gitlab/ssl'
    shm_size: '256m'
  runner:
    image: gitlab/gitlab-runner
    restart: always
    volumes:
      - './runner-config/:/etc/gitlab-runner/'
      - './certs/gitlab.mysite.com_CA.pem:/etc/gitlab-runner/certs/ca.crt'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      gitlab-net:

networks:
  gitlab-net:
    driver: bridge